name: cms

services:
  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "2345:5432"
